name: abseil-cpp
description: 'Builds and installs `abseil/abseil-cpp`'
branding:
  icon: package
  color: yellow

inputs:
  cmake-build-args:
    description: "arguments to pass to CMake"
    required: false
    default: "-DCMAKE_CXX_STANDARD=17 -DABSL_PROPAGATE_CXX_STD=ON -DABSL_ENABLE_INSTALL=ON -DBUILD_TESTING=off"
  cmake-version:
    description: "version of CMake to use"
    required: false
    default: ""
  abseil-version:
    description: "tag or ref of `abseil/abseil-cpp`"
    required: false
    default: "20240722.0"

runs:
  using: composite
  steps:
    - uses: jwlawson/actions-setup-cmake@802fa1a2c4e212495c05bf94dba2704a92a472be # v2.0.2
      with:
        cmake-version: ${{ inputs.cmake-version }}
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        repository: abseil/abseil-cpp
        ref: ${{ inputs.abseil-version }}
        path: ./_abseil-cpp/
    - shell: bash
      run: |
        mkdir build/ && cd build/
        cmake ${{ inputs.cmake-build-args }} ..
        sudo make install
      working-directory: ./_abseil-cpp/
    - shell: bash
      run: rm -rf ./_abseil-cpp/
