name: setup-abseil-cpp
description: 'Builds and installs `abseil/abseil-cpp`'
branding:
  icon: package
  color: yellow

inputs:
  cmake-build-args:
    description: "arguments to pass to CMake"
    required: false
    default: "-DCMAKE_CXX_STANDARD=17 -DABSL_PROPAGATE_CXX_STD=ON -DABSL_ENABLE_INSTALL=ON -DBUILD_TESTING=off"
  cmake-version:
    description: "version of CMake to use"
    required: false
    default: ""
  abseil-version:
    description: "tag or ref of `abseil/abseil-cpp`"
    required: false
    default: "20240722.0"

runs:
  using: composite
  steps:
    - uses: jwlawson/actions-setup-cmake@802fa1a2c4e212495c05bf94dba2704a92a472be # v2.0.2
      with:
        cmake-version: ${{ inputs.cmake-version }}
    - if: inputs.abseil-version != ''
      id: build-cache
      uses: actions/cache/restore@6849a6489940f00c2f30c0fb92c6274307ccb58a # v4.1.2
      with:
        path: ./_abseil-cpp/
        key: abseil-cpp-${{ inputs.abseil-version }}-${{ runner.os }}-${{ runner.arch }}-cmake-${{ inputs.cmake-build-args }}
    - if: steps.build-cache.outputs.cache-hit != 'true'
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        repository: abseil/abseil-cpp
        ref: ${{ inputs.abseil-version }}
        path: ./_abseil-cpp/
    - if: steps.build-cache.outputs.cache-hit != 'true'
      shell: bash
      run: mkdir ./_abseil-cpp/build/
    - if: steps.build-cache.outputs.cache-hit != 'true'
      shell: bash
      run: cmake ${{ inputs.cmake-build-args }} ..
      working-directory: ./_abseil-cpp/build/
    - shell: bash
      run: sudo cmake --build . --parallel=8 --target=install
      working-directory: ./_abseil-cpp/build/
    - if: steps.build-cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@6849a6489940f00c2f30c0fb92c6274307ccb58a # v4.1.2
      with:
        path: ./_abseil-cpp/
        key: abseil-cpp-${{ inputs.abseil-version }}-${{ runner.os }}-${{ runner.arch }}-cmake-${{ inputs.cmake-build-args }}
    - shell: bash
      run: rm -rf ./_abseil-cpp/
