name: test

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  action:
    strategy:
      matrix:
        runs-on:
          - ubuntu-latest
          - macos-13
          - macos-latest
      fail-fast: false
    runs-on: ${{ matrix.runs-on }}
    steps:
      - run: |
          gcc -print-search-dirs
          clang -print-search-dirs
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ./
      - run: mkdir hello_world/build/
      - run: cmake ..
        working-directory: hello_world/build/
      - run: cmake --build . --target hello_world
        working-directory: hello_world/build/
      - run: ./hello_world
        working-directory: hello_world/build/
