name: test

on:
  pull_request:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  action:
    strategy:
      matrix:
        runs-on:
          - ubuntu-latest
          - macos-13
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ./
      - run: mkdir ./build/
      - run: |
          cmake ..
          cmake --build . --target hello_world
        working-directory: ./build/
      - run: ./build/hello_world
        working-directory: ./build/
