name: test

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  action:
    strategy:
      matrix:
        runs-on:
          - ubuntu-latest
          - macos-13
          - macos-latest
      fail-fast: false
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: ./
      - run: mkdir hello_world/build/
      - run: cmake ..
        working-directory: hello_world/build/
      - run: cmake --build . --target hello_world
        working-directory: hello_world/build/
      - run: ./hello_world
        working-directory: hello_world/build/
